### ISSUE TITLE
el editor nano (y tambien vim) me dan un error que me impiden correr scripts

### ISSUE THREAD

**Issue by ramgonman** [ramgonman/decont#1]
El error que veo (solo te doy un ejemplo, porque me ha pasado desde ayer en varios scripts que intenté crear) es el siguiente

index.sh: línea 25: error sintáctico: no se esperaba el final del archivo

el problema es que la línea 25 de dicho script no existe. No puedo progresar con este problema. También he abierto con vim este script y no se ve nada que justifique el que aparezca dicho comentario

**Comment by tdido** [comment]
Acabo de bajar tu código del repositorio y no tengo problemas en abrir ninguno de los scripts, incluyendo el "index.sh". 

Primero, ¿el código que te da problemas es el que está en el repositorio?

Si es así, ¿me pasarías el comando exacto o la secuencia de acciones que te cause el error?

**Comment by ramgonman** [comment]
De momento sólo he hecho un commit y un push del download.sh script parte de la pipeline que nos pediste. Con ese script no he tenido ningún problema y lo testé. Estoy trabajando con un repositorio decont de tu github del cual hice un fork y luego cloné en mi ordenador el repositorio decont hace ya semanas.
Lo único que hice (este problema empezó ayer, antes no lo había tenido) es usar el editor nano para escribir el script index.sh, empezando por tu script llamado del mismo modo.
nano index.sh
Tras abrirse en la consola dicho script en nano, empecé a escribir y fui salvando con CTRL_X y luego confirmando que quería salvar el buffer nuevo. Creo recordar que también quité las líneas comentadas por ti en dicho script desde nano usando el comando CTRL_K que borra de línea en línea. Acabo de probar a hacer
bash merge_fastqs.sh, y ocurre lo mismo
merge_fastqs.sh: línea 14: error sintáctico: no se esperaba el final del archivo
Sin embargo, el script pipeline.sh aunque no lo he finalizado no da ese error al intentar bash pipeline.sh
No sé qué hacer.

**Comment by tdido** [comment]
OK, necesitaría ver los script que te dan error. Si podés publicarlos en un repo bien, si no adjuntalos aquí mismo.

**Comment by ramgonman** [comment]
Te paso los scripts index.sh, merge_fastqs.sh. Por favor ten en cuenta que no son los definitivos y por eso no he hecho commits de éstos, ya que antes tendría que testarlos y por este proble
[archivo.tar.gz](https://github.com/ramgonman/decont/files/10237129/archivo.tar.gz)
ma que te cuento no tengo manera de hacerlo por el error que da la sensación de que la última línea de los scripts que dan problema tienen algo pero no se ve nada ni en nano ni en vim.

**Comment by tdido** [comment]
Te falta el "fi" al finalizar la estructura del if:

```bash
if [condición]
then
   comando
fi
```
